# Generated by Django 2.0.3 on 2018-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180923_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='validity',
            field=models.IntegerField(default=0),
        ),
    ]
