# Generated by Django 2.0.3 on 2018-09-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_answer_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='answer',
        ),
        migrations.AlterField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main_app.Question'),
        ),
    ]
