# Generated by Django 2.0.3 on 2018-09-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20180924_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Upvote', 'Upvote'), ('Downvote', 'Downvote')], max_length=50)),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main_app.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_votes', to='main_app.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voteans',
            unique_together={('answer', 'user', 'type')},
        ),
    ]
